# Generated by Django 3.0.5 on 2024-09-17 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_question_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='exam',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='date',
            new_name='date_attempted',
        ),
        migrations.AddField(
            model_name='examresult',
            name='time_spent',
            field=models.DurationField(default=0.0002615670774238549),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
