# Generated by Django 3.0.5 on 2024-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20240917_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
