# Generated by Django 3.0.5 on 2024-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20240917_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
